---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app.kubernetes.io/name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: techblog-v1
  namespace: dev
spec:
  selector:
    app: techblog-v1
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techblog-v1
  namespace: dev
spec:
  selector:
    matchLabels:
      app: techblog-v1
  template:
    metadata:
      labels:
        app: techblog-v1
    spec:
      containers:
      - name: techblog-v1
        image: kristjanvoolaid/techblog:v1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: techblog-v2
  namespace: dev
spec:
  selector:
    app: techblog-v2
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techblog-v2
  namespace: dev
spec:
  selector:
    matchLabels:
      app: techblog-v2
  template:
    metadata:
      labels:
        app: techblog-v2
    spec:
      containers:
      - name: techblog-v2
        image: kristjanvoolaid/techblog:v2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: techblog-v3
  namespace: dev
spec:
  selector:
    app: techblog-v3
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techblog-v3
  namespace: dev
spec:
  selector:
    matchLabels:
      app: techblog-v3
  template:
    metadata:
      labels:
        app: techblog-v3
    spec:
      containers:
      - name: techblog-v3
        image: kristjanvoolaid/techblog:v3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
